version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Automatic updates for these are disabled as they are updated manually to
      # align with platform dependencies defined at
      # https://github.com/openshift/console.
      - dependency-name: "k8s.io/*"
      - dependency-name: "helm.sh/*"
      - dependency-name: "github.com/helm/*"
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: "weekly"
    groups:
      actions:
        applies-to: "version-updates"
        patterns:
          - "*"
