name: Unit Tests
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [ main ]

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        permissions:
          contents: read

        steps:
            - name: Checkout changes
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false
            - name: Setup Go
              uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
              with:
                go-version-file: go.mod
                
            - name: Ensure Modules
              run: make tidy

            - name: Build Binary
              run: make bin

            - name: Run tests
              run: |
                  # Run go tests
                  make test
                  if [[ -n $(git status -s) ]]
                  then
                    echo "go test - errors running go tests : $(git status -s)"
                    exit 1
                  fi
