name: Golang Style

on:
  pull_request:
    paths:
    - '**.go'

jobs:
  enforce:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod

    - name: Ensure Modules
      run: make tidy

    - name: Ensure Formatting
      run: make fmt

    - name: Run Linters
      run: make lint

    - name: Build Binary
      run: make bin