name: GoSec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Security scan
        shell: bash
        run: |
            if ! make gosec
            then
              echo "gosec scanner failed to run "
              exit 1
            fi

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: gosec.sarif