name: GoSec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Security scan
        shell: bash
        run: |
            if ! make gosec
            then
              echo "gosec scanner failed to run "
              exit 1
            fi

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: gosec.sarif