name: GoSec

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Security scan
        shell: bash
        run: |
            if ! make gosec
            then
              echo "gosec scanner failed to run "
              exit 1
            fi

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: gosec.sarif