name: Python Style

on:
  pull_request:
    paths:
    # Only trigger on changes to Python source.
    - 'scripts/**.py'
    - 'tests/**.py'
    - 'scripts/requirements.txt'
    - 'scripts/pyproject.toml'
    - 'scripts/setup.py'
    - 'scripts/setup.cfg'

jobs:
  enforce:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Install style tooling
      run: make venv.codestyle

    - name: Run formatter
      run: make py.ci.format

    - name: Run linter
      run: make py.lint
